tasks:
  - init: yarn install && yarn build
    command: yarn dev

vscode:
  extensions:
    - christian-kohler.path-intellisense
    - graphql.vscode-graphql
    - oderwat.indent-rainbow
    - vue.volar
    - bradlc.vscode-tailwindcss
    - aaron-bond.better-comments
    - GraphQL.vscode-graphql
