query getUserByUsername($username: String!) {
	appusers(filter: { username: { _eq: $username } }) {
		username
		avatar
	}
}
query login($username: String!, $password: String!) {
	appusers(
		filter: {
			username: { _eq: $username }
			_and: { password: { _eq: $password } }
		}
	) {
		id
	}
}
