mutation Login($email: String!, $password: String!) {
	auth_login(email: $email, password: $password,mode: json) {
		access_token
		expires
		refresh_token
	}
}
mutation RefreshToken($refresh_token: String!) {
	auth_refresh(refresh_token: $refresh_token , mode: json) {
		access_token
		refresh_token
	}
}

mutation Logout($token: String!) {
	auth_logout(refresh_token: $token)
}

mutation CreateUser($userData: create_directus_users_input!) {
	create_users_item(data: $userData) {
		email,
		role
	}
}

query GetUserByMail($email: String!) {
	users(filter: { email: { _eq: $email } }) {
		first_name
		last_name
		email
		location
		title
		description
		avatar
	}
}
